# frozen_string_literal: true

require 'tmpdir'

# The engine-computed nodal corrections (HARMONICS_NODAL=legacy, and any year
# outside the TCD table in the default tcd mode) against the 780-point oracle in
# spec/fixtures/harmonics/nodal_oracle.json. The oracle was generated by running
# that path at commit 05076b4 (see the file's "generated_from"), so this spec
# pins its behaviour: f, V0+u and u for the 13 constituents it covers, to 1e-9.
RSpec.describe Harmonics::Engine, 'nodal corrections vs the oracle' do
    oracle = JSON.parse(File.read(File.expand_path('../../fixtures/harmonics/nodal_oracle.json', __dir__)))
    tol = 1e-9
    constituents = oracle.fetch('constituents').sort
    groups = oracle.fetch('cases').group_by { |c| c.values_at('year', 'month', 'day', 'hour', 'shift_hours') }
    tcd_years = 1700..2100

    let(:logger) { Logger.new('/dev/null') }

    around do |ex|
        saved = ENV['HARMONICS_NODAL']
        ex.run
    ensure
        saved.nil? ? ENV.delete('HARMONICS_NODAL') : ENV['HARMONICS_NODAL'] = saved
    end

    # Circular difference in degrees, in [-180, 180).
    def circ(a, b)
        ((a - b + 180.0) % 360.0) - 180.0
    end

    def engine_for(mode, dir)
        ENV['HARMONICS_NODAL'] = mode
        described_class.new(logger, dir)
    end

    def expect_oracle(factors, cases, tol)
        cases.each do |c|
            nf = factors.fetch(c['constituent'])
            label = "#{c['constituent']} #{c.values_at('year', 'month', 'day', 'hour', 'shift_hours').inspect}"
            expect((nf['f'] - c['f']).abs).to be <= tol, "f for #{label}"
            expect(circ(nf['V0'] + nf['u'], c['V0_plus_u_mod360']).abs).to be <= tol, "V0+u for #{label}"
            expect(circ(nf['u'], c['u_mod_pm180']).abs).to be <= tol, "u for #{label}"
        end
    end

    it 'has 780 points: 13 constituents x 12 years x 5 instants' do
        expect(oracle.fetch('cases').size).to eq(780)
        expect(groups.size).to eq(60)
    end

    # The legacy mode computes every year; the tcd mode computes only the
    # years outside its table, so only those are checked there.
    { 'legacy' => ->(_) { true }, 'tcd' => ->(y) { !tcd_years.cover?(y) } }.each do |mode, applies|
        describe "#{mode} mode, through get_nodal_factors" do
            groups.select { |(year, *), _| applies.call(year) }.each do |(year, month, day, hour, shift), cases|
                it "matches the oracle for #{year}-#{month}-#{day} #{hour}h m=#{shift}" do
                    Dir.mktmpdir do |dir|
                        computed = engine_for(mode, dir).send(:get_nodal_factors, year, month, day, shift, hour)
                        expect(computed.keys.sort).to eq(constituents)
                        expect_oracle(computed, cases, tol)

                        # A second engine reads the nodal cache file the first one wrote.
                        cached = engine_for(mode, dir).send(:get_nodal_factors, year, month, day, shift, hour)
                        expect(cached).to eq(JSON.parse(computed.to_json))
                    end
                end
            end
        end
    end

    # The same corrections as generate_predictions applies them: a station with
    # amplitude 1 and phase 0 for each of the 13 constituents, predicted at the
    # instant the oracle's u and f are for, must give sum(f * cos(speed*t + V0+u)).
    describe 'through generate_predictions' do
        [['legacy', 2026, 7, 2, 0.0], ['legacy', 1600, 7, 2, 0.0], ['legacy', 2400, 3, 15, 9.5],
         ['tcd', 1600, 7, 2, -5.0], ['tcd', 2400, 12, 31, 0.0], ['tcd', 2101, 3, 15, 9.5]].each do |mode, year, month, day, shift|
            it "#{mode} mode, #{year}-#{month}-#{day} 12:00 UTC, m=#{shift}" do
                cases = groups.fetch([year, month, day, 12, shift])
                Dir.mktmpdir do |dir|
                    engine = engine_for(mode, dir)
                    engine.stations
                    engine.stations_cache['RNORACLE'] = {
                        'constituents' => constituents.map { |n| { 'name' => n, 'amp' => 1.0, 'phase' => 0.0 } },
                        'datum_offset' => 0.0, 'meridian' => '00:00:00', 'units' => 'meters'
                    }
                    at = Time.utc(year, month, day, 12)
                    got = engine.generate_predictions('RNORACLE', at, at, step_seconds: 3600, meridian_override: shift)
                    t = (at - Time.utc(year, 1, 1)) / 3600.0 - shift
                    want = cases.sum do |c|
                        c['f'] * Math.cos((engine.speeds.fetch(c['constituent']) * t + c['V0_plus_u_mod360']) * Math::PI / 180.0)
                    end
                    expect(got.size).to eq(1)
                    expect(got.first['height']).to be_within(1e-8).of(want)
                end
            end
        end
    end
end
