# frozen_string_literal: true

require 'tmpdir'
require 'digest'

# The engine-computed nodal corrections (HARMONICS_NODAL=legacy, and any year
# outside the TCD table in the default tcd mode) against the 780-point oracle in
# spec/fixtures/harmonics/nodal_oracle.json. The oracle was generated by running
# that path at commit 05076b4 (see the file's "generated_from"), so this spec
# pins its behaviour for the 13 constituents it covers: f and u to 1e-9, and
# V0+u to 4e-9 degrees. V0 sums raw longitudes; the largest |V0| in the oracle
# is 7.0e6 degrees, below 2^23, where one double ulp is 2^-30 (about 9.3e-10
# degrees). The worst V0+u residual is 1.97e-9 degrees, about 2.1 ulps, from
# rounding in the intermediate sums. 4e-9 degrees is about 0.5 microseconds of
# M2 phase.
#
# The 4e-9 agreement holds for meridian shifts that are binary fractions of an
# hour (0, -5 and 9.5 h), which are all the oracle uses. For a shift such as
# 1/3 hour (measured over 1600-2400 in 25-year steps, shifts 1/3, -1/3 and
# 5/3 h), old and new V0+u differ by up to 1.7e-8 degrees, about 2
# microseconds of M2 phase. The new value is the more accurate one: it is
# within 1.7e-9 degrees of an exact Rational evaluation, and the old one was
# up to 1.8e-8 degrees from it. The oracle's own "tolerance" block says 1e-9 for every field;
# the 4e-9 for V0+u is the coordinator's decision (docs/nodal-cleanroom/PROVENANCE.md).
RSpec.describe Harmonics::Engine, 'nodal corrections vs the oracle' do
    # The oracle is pinned by its SHA-256 (as in spec/unit/nodal_schureman_spec.rb),
    # so a changed fixture stops this file at load, even when it runs alone.
    oracle_sha256 = '236929d0c62da30b6b2cbed0d7322a466afd3e77ef4889b595bab0bdd04f7367'
    oracle_bytes = File.binread(File.expand_path('../../fixtures/harmonics/nodal_oracle.json', __dir__))
    actual_sha256 = Digest::SHA256.hexdigest(oracle_bytes)
    raise "oracle SHA-256 mismatch: expected #{oracle_sha256}, got #{actual_sha256}" unless actual_sha256 == oracle_sha256

    oracle = JSON.parse(oracle_bytes)
    tol = { f: 1e-9, u: 1e-9, v0u: 4e-9 }
    constituents = oracle.fetch('constituents').sort
    groups = oracle.fetch('cases').group_by { |c| c.values_at('year', 'month', 'day', 'hour', 'shift_hours') }
    oracle_years = groups.keys.map(&:first).uniq
    # The TCD year range the oracle was generated against. Each tcd-mode
    # example checks that the engine's real table agrees for its year.
    fixture_tcd_years = Range.new(*oracle.fetch('generated_from').fetch('tcd_year_range'))

    let(:logger) { Logger.new('/dev/null') }

    # The years the engine's TCD file has tables for (in tcd mode, only years
    # outside them reach the computed corrections), read lazily from the real
    # table, once. Without the TCD data file (data/latest-xtide.tcd, or
    # XTIDE_FILE) the examples that need it fail, as the other harmonics specs
    # do; they are not skipped. The legacy get_nodal_factors examples do not
    # need it.
    tcd_years_memo = nil
    define_method(:tcd_years) do
        tcd_years_memo ||= described_class.new(Logger.new(nil), Dir.tmpdir).send(:tcd_nodal_table)['years']
    end

    around do |ex|
        saved = ENV['HARMONICS_NODAL']
        ex.run
    ensure
        saved.nil? ? ENV.delete('HARMONICS_NODAL') : ENV['HARMONICS_NODAL'] = saved
    end

    # Circular difference in degrees, in [-180, 180).
    def circ(a, b)
        ((a - b + 180.0) % 360.0) - 180.0
    end

    def engine_for(mode, dir)
        ENV['HARMONICS_NODAL'] = mode
        described_class.new(logger, dir)
    end

    def expect_oracle(factors, cases, tol)
        cases.each do |c|
            nf = factors.fetch(c['constituent'])
            label = "#{c['constituent']} #{c.values_at('year', 'month', 'day', 'hour', 'shift_hours').inspect}"
            expect((nf['f'] - c['f']).abs).to be <= tol[:f], "f for #{label}"
            expect(circ(nf['V0'] + nf['u'], c['V0_plus_u_mod360']).abs).to be <= tol[:v0u], "V0+u for #{label}"
            expect(circ(nf['u'], c['u_mod_pm180']).abs).to be <= tol[:u], "u for #{label}"
        end
    end

    it 'has 780 points: 13 constituents x 12 years x 5 instants' do
        expect(oracle.fetch('cases').size).to eq(780)
        expect(groups.size).to eq(60)
    end

    it 'has oracle years both inside and outside the TCD table' do
        expect(oracle_years.count { |y| tcd_years.cover?(y) }).to be > 0
        expect(oracle_years.count { |y| !tcd_years.cover?(y) }).to be > 0
    end

    # The legacy mode computes every year. The tcd mode computes only the
    # years outside its table; for a year inside it, the TCD tables are used
    # and NodalSchureman is not called (their values are pinned elsewhere, in
    # nodal_mode_spec).
    groups.each do |(year, month, day, hour, shift), _|
        next unless fixture_tcd_years.cover?(year)

        it "tcd mode, #{year}-#{month}-#{day} #{hour}h m=#{shift} (inside the TCD table): does not call NodalSchureman" do
            expect(tcd_years).to cover(year)
            Dir.mktmpdir do |dir|
                e = engine_for('tcd', dir)
                expect(NodalSchureman).not_to receive(:compute)
                expect(e.send(:get_nodal_factors, year, month, day, shift, hour).size).to be > constituents.size
            end
        end
    end

    { 'legacy' => ->(_) { true }, 'tcd' => ->(y) { !fixture_tcd_years.cover?(y) } }.each do |mode, applies|
        describe "#{mode} mode, through get_nodal_factors" do
            groups.select { |(year, *), _| applies.call(year) }.each do |(year, month, day, hour, shift), cases|
                it "matches the oracle for #{year}-#{month}-#{day} #{hour}h m=#{shift}" do
                    expect(tcd_years).not_to cover(year) if mode == 'tcd'

                    Dir.mktmpdir do |dir|
                        computed = engine_for(mode, dir).send(:get_nodal_factors, year, month, day, shift, hour)
                        expect(computed.keys.sort).to eq(constituents)
                        expect_oracle(computed, cases, tol)

                        # A second engine serves the nodal cache file the first one
                        # wrote: it must not compute again.
                        second = engine_for(mode, dir)
                        expect(NodalSchureman).not_to receive(:compute)
                        cached = second.send(:get_nodal_factors, year, month, day, shift, hour)
                        expect(cached).to eq(JSON.parse(computed.to_json))
                    end
                end
            end
        end
    end

    # The same corrections as generate_predictions applies them: a station with
    # amplitude 1 and phase 0 for each of the 13 constituents, predicted at the
    # instant the oracle's u and f are for, must give sum(f * cos(speed*t + V0+u)).
    describe 'through generate_predictions' do
        [['legacy', 2026, 7, 2, 0.0], ['legacy', 1600, 7, 2, 0.0], ['legacy', 2400, 3, 15, 9.5],
         ['tcd', 1600, 7, 2, -5.0], ['tcd', 2400, 12, 31, 0.0], ['tcd', 2101, 3, 15, 9.5]].each do |mode, year, month, day, shift|
            it "#{mode} mode, #{year}-#{month}-#{day} 12:00 UTC, m=#{shift}" do
                expect(tcd_years).not_to cover(year) if mode == 'tcd'
                cases = groups.fetch([year, month, day, 12, shift])
                Dir.mktmpdir do |dir|
                    engine = engine_for(mode, dir)
                    engine.stations
                    engine.stations_cache['RNORACLE'] = {
                        'constituents' => constituents.map { |n| { 'name' => n, 'amp' => 1.0, 'phase' => 0.0 } },
                        'datum_offset' => 0.0, 'meridian' => '00:00:00', 'units' => 'meters'
                    }
                    at = Time.utc(year, month, day, 12)
                    got = engine.generate_predictions('RNORACLE', at, at, step_seconds: 3600, meridian_override: shift)
                    t = (at - Time.utc(year, 1, 1)) / 3600.0 - shift
                    want = cases.sum do |c|
                        c['f'] * Math.cos((engine.speeds.fetch(c['constituent']) * t + c['V0_plus_u_mod360']) * Math::PI / 180.0)
                    end
                    expect(got.size).to eq(1)
                    expect(got.first['height']).to be_within(1e-8).of(want)
                end
            end
        end
    end
end
